#ifndef REDISMODULE_EXPORT_H
#define REDISMODULE_EXPORT_H

#ifdef REDISMODULE_LIBRARY
#  define REDISMODULESHARED_EXPORT Q_DECL_EXPORT
#else
#  define REDISMODULESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // REDISMODULE_EXPORT_H
